theme: jekyll-theme-cayman
title: Specvis Desktop
description: Specvis Desktop is a free, open-source and academically verified application designed for visual field examination in humans.
show_downloads: true